### ISSUE TITLE
A letter for the code.

### ISSUE THREAD

**Issue by cuitdongxiaofeng** [StongeEtienne/trimeshpy#1]
Dear Sir,
I am reading your paper on SET.I want to reproduce the process in your paper, but the scilpy toolkit can't be downloaded for the time being. When will it be convenient for you to provide the code about scilpy?
I am looking forward to your reply.

**Comment by StongeEtienne** [comment]
Hi,
The Scilpy Gihub should be available soon (this year).
We currently work to improve the Scilpy library, simplify it and remove some dependency.

However, with this Trimeshpy library you can already compute the _"surface flow"_ (detailed in SET) with the "positive_mass_stiffness_smooth" (see  "trimeshpy/examples/visu_test.py" for usage).

Missing functions from Scilpy are only combine this _"surface flow"_ to [dipy](https://github.com/nipy/dipy) tractography algorithms. I'm currently updating those script to work with the current Dipy version, and also to make them easier of use.

Thanks,

**Comment by kristianeschenburg** [comment]
Hi @StongeEtienne,  I was wondering what the status was on incorporating the surfaceflow into Dipy?  Do you have a preliminary / beta version working yet?

**Comment by StongeEtienne** [comment]
@kristianeschenburg  Currently, the _surface flow_ from SET is already in this repository, "positive_mass_stiffness_smooth". It generate a final surface, with a memmap saving each step of the flow. 

However, since it is about geometry processing and not diffusion MRI, Dipy did not want to include the code (or add new dependency to a small non reviewed project). With growing of the community, they might change their mind.

I have, in our SCIL lab repository  https://github.com/scilus/scilpy (but our private version), all the code needed to:

1. Create mask/seeding labels from Freesurfer .annot (GM regions of interest) 
2. Script to compute the Surface flow, and generate the small beginning segments
3. Functions to generate Surface Seeds from surfaces (very similar to what you proposed) 
4. Script to start Dipy tractography from those seeds
5. Script to compute Enpoints collisions from streamlines
6. Mapping from streamlines endpoints to cortical label (connectivity analyses)

We plan on releasing Scilpy on GitHub "soon", and normally push major tools / functions in Dipy.
Sadly, TriMeshPy and my surface codes heavily rely on VTK and I'm the only one developing it.

Nonetheless, it would be good to make it available and have more people working on the project !

**Comment by kristianeschenburg** [comment]
@StongeEtienne I'd be interested in working on it with you, if you're willing to open up your work so far.  I've had a read through your trimeshpy library as it stands now -- it's quite sophisticated -- and I'm also interested in learning about the list of to-do items you noted above, for personal growth as well as out of necessity and relationship for my own work!
